version: '3'

services:
  app:
    build:
      dockerfile: Dockerfile
      context: ./
    container_name: cli
    working_dir: /app
    tty: true
    stdin_open: true
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development # Node.js の環境変数を設定
volumes:
  node_modules:
